library:
  source-dirs: src
tests:
  opaleye-example-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opaleye-example
    - hspec
copyright: 2020 Barry Moore
maintainer: moore0557@gmail.com
dependencies:
- text
- base >= 4.7 && < 5
- opaleye
- postgresql-simple
- product-profunctors
name: opaleye-example
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Barry Moore
github: barrymoo/opaleye-example
license: BSD3
executables:
  opaleye-example-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opaleye-example
description: Please see the README on GitHub at <https://github.com/barrymoo/opaleye-example#readme>
