library:
  source-dirs: src
tests:
  beam-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beam
    - hspec
    - directory
copyright: 2020 Barry Moore
maintainer: moore0557@gmail.com
dependencies:
- system-fileio
- base >= 4.7 && < 5
- beam-core
- beam-sqlite
- beam-migrate
- sqlite-simple
- text
name: beam
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Barry Moore
github: barrymoo/beam
license: BSD3
executables:
  beam-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beam
description: Please see the README on GitHub at <https://github.com/barrymoo/beam#readme>
